### ISSUE TITLE
Capítulo 2 - Editando

### ISSUE THREAD

**Issue by cassiobotaro** [cassiobotaro/vimbook#1]

**Comment by gtsalles** [comment]
Eu faço esse :)

**Comment by cassiobotaro** [comment]
:+1:

**Comment by cassiobotaro** [comment]
@gtsalles algum progresso?

**Comment by gtsalles** [comment]
Comecei mas não terminei, vou comitar algo até o fim de semana.

**Comment by cassiobotaro** [comment]
:+1:

**Comment by cassiobotaro** [comment]
ping @gtsalles

**Comment by gtsalles** [comment]
Vou corrigir os links entre os tópicos, fazer uma revisão nas aspas que ficaram meio bugadas e adicionar ao sumário pra fazer mais um commit e fechar essa issue.
