### ISSUE TITLE
Issue para capitulos

### ISSUE THREAD

**Issue by brunopulis** [cassiobotaro/vimbook#16]
@cassiobotaro Acho bacana criar uma Issue fixa ou até mesmo um Cnangelog para os contribuidores do projeto saberem em qual capitulo podem mexer :+1:

**Comment by cassiobotaro** [comment]
Alguma sugestão?
Eu deixei todos os capítulos como issues e a medida que a pessoa vai escolhendo, ela coloca nome na issue. Não consegui pensar em uma outra maneira de oraganização.

**Comment by cassiobotaro** [comment]
Criei uma issue para isto, é a #20
