### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [cassiobotaro/vimbook#2]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by cassiobotaro** [comment]
@codehangen está sim, a ideia de transforma-lo em markdown é justamente para facilitar na contribuição.

Pode abrir issues com suas ideias que vamos conversando.

**Comment by ghost** [comment]
Oi cassiobotaro.

> @codehangen está sim, a ideia de transforma-lo em markdown é justamente para facilitar na contribuição.
> Pode abrir issues com suas ideias que vamos conversando.

vou ver como posso contribuir com esse projeto e valeu pela resposta.

*tenha um ótimo dia e obrigado por responder minha dúvida*
