### ISSUE TITLE
Progresso do projeto

### ISSUE THREAD

**Issue by cassiobotaro** [cassiobotaro/vimbook#20]
Aqui é possível ver o andamento do projeto, quais capítulos faltam e quais as tarefas ainda precisam ser realizadas.

- [ ] Melhor diagramação(disposição dos capítulos)
- [x] Capítulo 2
- [x] Capítulo 5
- [x] Capítulo 14
- [x] Capítulo 15
- [x] Referências

**Comment by brunopulis** [comment]
@cassiobotaro Para os links quebrados recomendo usar o Travis CI =)

**Comment by drgarcia1986** [comment]
@cassiobotaro gostaria de ajudar com os links quebrados.

Vi nos capítulos 1 e 3 que todos os links estão vazios, qual a forma padrão que eles devem ser preenchidos para o gitbook entender?

**Comment by cassiobotaro** [comment]
Acho que te respondi no PR, mas para registro e consulta de outros, links internos do livro tem o seguinte formato `[texto](capitulo_x/nome_do_arquivo.md)`

**Comment by drgarcia1986** [comment]
Foi sim, show :+1: 
O que acha de criar uma issue com uma lista dos capítulos para revisar os links (assim como foi feito com as aspas)?

**Comment by cassiobotaro** [comment]
Done! Pode ser visto em #26

**Comment by cassiobotaro** [comment]
Transferi as referências para uma issue própria. #44
