### ISSUE TITLE
Excesso de aspas (ou apenas desnecessárias)

### ISSUE THREAD

**Issue by drgarcia1986** [cassiobotaro/vimbook#21]
Notei (pelo menos no primeiro capitulo) que comando estão usando a notação '`comando`', ou seja já possuem destaque graças ao _``_ e ainda sim estão com aspas simples (herança do livro antigo provavelmente).

Acho que poderíamos simplificar apenas com o highlight, acredito que fica mais confortável para o leitor.

- [x] Capítulo 1
- [x] Capítulo 2
- [x] Capítulo 3
- [x] Capítulo 4
- [x] Capítulo 5
- [x] Capítulo 6
- [x] Capítulo 7
- [x] Capítulo 8
- [x] Capítulo 9
- [x] Capítulo 10
- [x] Capítulo 11
- [x] Capítulo 12
- [x] Capítulo 13
- [x] Capítulo 14
- [x] Capítulo 15

**Comment by cassiobotaro** [comment]
Eu tinha isto em mente, estava esperando apenas terminar de portar todos os capítulos para começar estas correções.
Os capítulos markdown foram gerados "automagicamente " :sparkles:, logo algumas heranças terão de ser revistas,  como esta e também alguns links e número de páginas.

A decisão é colocar somente o highlight e revisarmos os capítulos anteriores corrigindo isto.

**Comment by cassiobotaro** [comment]
Acho que uma task list com os cápitulos já resolve, a medida que cada caíputo for revisado, a pessoa marca e avisa qual capítulo foi revisado.

- [ ] Capítulo 1
- [ ] Capítulo 1
- [ ] Capítulo 1
- [ ] Capítulo 1
- [ ] Capítulo 1
- [ ] Capítulo 1
- [ ] Capítulo 1
- [ ] Capítulo 1

**Comment by drgarcia1986** [comment]
show, irei ajudar com isso então :+1:

**Comment by drgarcia1986** [comment]
Peguei o cap1 para resolver isso :rocket:

**Comment by drgarcia1986** [comment]
vou pegar o cap2

**Comment by drgarcia1986** [comment]
O capítulo 2 está ok se não me engano, vou pegar agora o capítulo 3

**Comment by drgarcia1986** [comment]
conferi o capítulo 4 e está ok :+1:

**Comment by drgarcia1986** [comment]
PR do cap7 está aberto

**Comment by drgarcia1986** [comment]
Revisando o capítulo 6

**Comment by drgarcia1986** [comment]
Capítulo 8 ok.

**Comment by drgarcia1986** [comment]
Estou verificando o cap12

**Comment by drgarcia1986** [comment]
Capítulo 11 comigo

**Comment by drgarcia1986** [comment]
conferindo cap13  (conferi alguns outros caps e estão ok)

**Comment by drgarcia1986** [comment]
DONE :rocket: :tada:
