### ISSUE TITLE
Revisão de links quebrados

### ISSUE THREAD

**Issue by cassiobotaro** [cassiobotaro/vimbook#26]
Aqui está uma lista com os capítulos para revisao de links quebrados:

Caso  inicie o processo de revisao de alguns dos capítulos, notique em comentário abaixo.

- [x] Capitulo 1
- [x] Capitulo 2
- [x] Capitulo 3
- [x] Capitulo 4
- [x] Capitulo 5
- [x] Capitulo 6
- [x] Capitulo 7
- [x] Capitulo 8
- [x] Capitulo 9
- [x] Capitulo 10
- [x] Capitulo 11
- [x] Capitulo 12
- [x] Capitulo 13
- [x] Capitulo 14
- [x] Capitulo 15

Descobri que referências a arquivos internos devem ser relativos

```diff
- no capítulo [Buscas e Substituições](capitulo_6/buscas_e_substituicoes.md)
+ no capítulo [Buscas e Substituições](../capitulo_6/buscas_e_substituicoes.md)
```

**Comment by drgarcia1986** [comment]
Cap1 ta comigo :rocket:

**Comment by drgarcia1986** [comment]
Cap2 comigo.

**Comment by drgarcia1986** [comment]
Cap3 abrindo PR e vou revisar tmbo cap 15

**Comment by drgarcia1986** [comment]
Peguei o cp4

**Comment by drgarcia1986** [comment]
cp5 está ok, já verifiquei :+1:

**Comment by drgarcia1986** [comment]
PR do cp7 está aberto

**Comment by drgarcia1986** [comment]
Estou revisando o capítulo 6

**Comment by cassiobotaro** [comment]
cp8 está comigo

**Comment by cassiobotaro** [comment]
8 e 9 conferidos, sem links quebrados.

**Comment by cassiobotaro** [comment]
iniciando revisão do capítulo 10

**Comment by cassiobotaro** [comment]
10 e 11 :ok_hand:

**Comment by drgarcia1986** [comment]
voltei, vou revisar o capítulo 12

**Comment by drgarcia1986** [comment]
12 e 13 estão ok :+1:

**Comment by drgarcia1986** [comment]
14 ok

**Comment by drgarcia1986** [comment]
Done :rocket: :tada:
