### ISSUE TITLE
sugestão: adicionar imagens do vim para facilitar a leitura

### ISSUE THREAD

**Issue by ghost** [cassiobotaro/vimbook#3]
Oi pessoal.

Uma ideia interessante que tive para facilitar a leitura do livro vimbook seria adicionar imagens do vim. As imagens poderiam ser em formato de png, jpeg, jpg ou gif. 

*conceito*
![image](https://user-images.githubusercontent.com/111701513/213052986-16af81c1-beac-4b4b-bf02-092b99e41210.png)

**img-descrição:** temos uma imagem no livro para facilitar a leitura.

*questionamento/feedback*
O que pensam dessa ideia de adicionar imagens do vim para a facilitar a leitura do livro?

**Comment by cassiobotaro** [comment]
Olá @codehangen , desculpa a demora na resposta. Gosto da ideia de adicionar imagens, porém o formato gif não acho interessante pois um dos planos é disponibilizar o livro em pdf e epub, que não suportam animações.
Você tem ideia de qual partes adicionar as imagens e quais imagens?

**Comment by ghost** [comment]
Oi cassiobotaro.

> Olá @codehangen , desculpa a demora na resposta. 

tudo bem mano.

> Gosto da ideia de adicionar imagens, 

valeu pelo feedback.

> porém o formato gif não acho interessante pois um dos planos é disponibilizar o livro em pdf e epub, que não suportam animações.

no caso de gif penso em adicionar no site: `https://cassiobotaro.dev/vimbook/capitulo_2/escrevendo_o_texto/`

> Você tem ideia de qual partes adicionar as imagens e quais imagens?

- penso em adicionar em todas as partes do livro mais essenciais como na introdução alguma imagem com um passo a passo.
- penso em adicionar imagens de acordo com o tópico do livro, mostrando uma imagem que corresponde ao texto com um passo a passo.

*o que pensa dessas ideias?*

**Comment by cassiobotaro** [comment]
> no caso de gif penso em adicionar no site: https://cassiobotaro.dev/vimbook/capitulo_2/escrevendo_o_texto/

Imgaem no formato `gif` é interessante em mídia digital, mas não funcionaria em PDF e e-pub. Como tenho planos de utilizar a renderização também nestes formatos, acho que inviabilizaria a ideia.

> penso em adicionar em todas as partes do livro mais essenciais como na introdução alguma imagem com um passo a passo.
> penso em adicionar imagens de acordo com o tópico do livro, mostrando uma imagem que corresponde ao texto com um passo a passo.

Eu acho sensacional, acho que agrega muito ter elementos visuais no livro.

Quer ajuda para mandar uma *pull request*?  Existe um guia sobre [como contribuir](https://github.com/cassiobotaro/vimbook/blob/main/CONTRIBUTING.md), mas se quiser podemos fazer um juntos e depois você submete as outras.

**Comment by ghost** [comment]
Oi cassiobotaro.

> Eu acho sensacional, acho que agrega muito ter elementos visuais no livro.

> Quer ajuda para mandar uma pull request? Existe um guia sobre [como contribuir](https://github.com/cassiobotaro/vimbook/blob/main/CONTRIBUTING.md), mas se quiser podemos fazer um juntos e depois você submete as outras.

vou fechar essa issue já que aceitou minha ideia e já que vou enviar um pull-request correspondente a essa ideia.

**Comment by cassiobotaro** [comment]
Desde já agradeço, @codehangen .
