### ISSUE TITLE
Padrão das notas de rodapé

### ISSUE THREAD

**Issue by drgarcia1986** [cassiobotaro/vimbook#30]
Notei que em alguns capítulos as notas de rodapé estão junto com a página do subcaptiulo (como é o caso da [introdução](https://cassiobotaro.gitbooks.io/vimbook/content/capitulo_1/introducao.html)) enquanto que em outros são nodas de rodapé para o capítulo inteiro (como é o caso do [capítulo 2](https://cassiobotaro.gitbooks.io/vimbook/content/capitulo_2/comparando_arquivos_com_vimdiff.html))

Acho que podemos padronizar do primeiro jeito, assim o leitor tem acesso as notas de rodapé da página que ele está lendo no momento.

**Comment by cassiobotaro** [comment]
O capitulo 2 está incorreto. Está relacionado com #32 .

**Comment by drgarcia1986** [comment]
:+1:

**Comment by cassiobotaro** [comment]
Já foi adicionado ao CONTRIBUTING
