### ISSUE TITLE
Padrão em links de capítulos

### ISSUE THREAD

**Issue by drgarcia1986** [cassiobotaro/vimbook#31]
Alguns links estão com o título do capítulo (como é o caso do [capítulo 3](https://cassiobotaro.gitbooks.io/vimbook/content/capitulo_3/movendo-se_no_documento.html)) enquanto que outros estão com a numeração do capítulo (como no caso do [capítulo 2](https://cassiobotaro.gitbooks.io/vimbook/content/capitulo_2/editando_em_modo_comando.html))

Sinceramente não sei dizer qual padrão é o melhor, mas podemos escolher um e revisar os capítulos para deixar tudo uniforme.

**Comment by cassiobotaro** [comment]
Acho que o melhor é não colocar por numeração, afinal, quando mudar podemos ter problema. Acho que convém adicionar esta informação no CONTRIBUTING neh?

**Comment by drgarcia1986** [comment]
Concordo :+1:

**Comment by cassiobotaro** [comment]
Padrão definido agora no CONTRIBUTING.
