### ISSUE TITLE
Remover quebra de linha das notas de rodapé

### ISSUE THREAD

**Issue by drgarcia1986** [cassiobotaro/vimbook#32]
Toda nota de rodapé que contem quebra de linha está aparecendo quebrada, [exemplo](https://cassiobotaro.gitbooks.io/vimbook/content/capitulo_1/instalacao_do_vim.html)

Acho que podemos revisar os capítulos e remover.

**Comment by cassiobotaro** [comment]
Acho que além de remover a quebra de linha, poderiamos renumerar as notas do rodapé, já que agora as notas são por página e não por arquivo como era o original. Exemplo: [aqui](https://cassiobotaro.gitbooks.io/vimbook/content/capitulo_1/instalacao_do_vim.html)

**Comment by drgarcia1986** [comment]
Boa, concordo, podemos partir do principio que cada página tem o seu "contador" de notas de rodapé, ou seja, em cada página as notas começam a partir do `1`

**Comment by cassiobotaro** [comment]
Também adicionado ao CONTRIBUTING, durante a revisão dos capítulos por links quabrados e outros, já revisamos isto também.
