### ISSUE TITLE
Capítulo 5 - Registros

### ISSUE THREAD

**Issue by cassiobotaro** [cassiobotaro/vimbook#4]

**Comment by gutierri** [comment]
Fazendo

**Comment by cassiobotaro** [comment]
@gutierri algum progresso neste capítulo?

**Comment by gutierri** [comment]
@cassiobotaro Pouco... Até esse fim de semana pretendo finalizar. Desculpe!

**Comment by cassiobotaro** [comment]
:+1: Tranquilo.

**Comment by cassiobotaro** [comment]
ping @gutierri

**Comment by cassiobotaro** [comment]
Acabei fazendo ele :neckbeard:
