### ISSUE TITLE
Arrow up e Arrow down

### ISSUE THREAD

**Issue by cassiobotaro** [cassiobotaro/vimbook#53]
Emoji infelizmente não funciona no livro. [Exemplo aqui](https://cassiobotaro.gitbooks.io/vimbook/content/capitulo_12/rolar_outra_janela.html).
Precisamos pensar em uma representação, que funcione em todos os formatos do livro.

**Comment by drgarcia1986** [comment]
Que pena, no #51 vou usar `Seta para Cima` e `Seta para Baixo` então até encontrarmos outra maneira, ok?

**Comment by cassiobotaro** [comment]
ok

**Comment by drgarcia1986** [comment]
Podemos tentar usar as setas UTF-8 ⬆⬇⬅➡
Farei um teste com o cp12, se der certo, atualizo o CONTRIBUTING e podemos revisar os outros capítulos e ir corrigindo.

**Comment by drgarcia1986** [comment]
Eu gostei :smile: 
https://cassiobotaro.gitbooks.io/vimbook/content/capitulo_12/mapeamentos_globais.html
