### ISSUE TITLE
Revisão das funções apresentadas no capítulo 12

### ISSUE THREAD

**Issue by drgarcia1986** [cassiobotaro/vimbook#61]
Acredito que a transição de LaTeX para markdown tenha quebrado alguns caracteres nas funções que são apresentadas no capítulo 12, acredito que podemos fazer uma task force para testa-las e valida-las (e talvez propor outras funções também bacanas)

**Comment by cassiobotaro** [comment]
Acha necessário uma lista de capítulos como fizemos nas outras revisões?

**Comment by drgarcia1986** [comment]
Nesse caso, acho que daria mais trabalho montar a lista do que validar os comandos.
IMO podemos seguir sem a lista.
