### ISSUE TITLE
Trocar blocos de higlight para o padrão markdown

### ISSUE THREAD

**Issue by drgarcia1986** [cassiobotaro/vimbook#62]
Atualmente os blocos de código e highlight estão com o padrão de tabulação, ex:
       
        for i in range(10)

Sugiro trocarmos para o padrão markdown para podermos usar highlights quando for de interesse:

```python
for i in range(10)
```
- [x] capitulo 1
- [x] capitulo 2
- [x] capitulo 3
- [x] capitulo 4
- [x] capitulo 5
- [x] capitulo 6
- [x] capitulo 7
- [x] capitulo 8
- [x] capitulo 9
- [x] capitulo 10
- [x] capitulo 11
- [x] capitulo 12
- [x] capitulo 13
- [x] capitulo 14
- [x] capitulo 15

**Comment by cassiobotaro** [comment]
Estou de acordo. Vamos iniciar isso adicionando isso ao CONTRIBUTING. Acha necessário uma lista de capítulos como fizemos nas outras revisões?

**Comment by drgarcia1986** [comment]
:+1: 
Sobre a lista, acho que é legal para ninguém atropelar os commits de outra pessoa.

**Comment by drgarcia1986** [comment]
vou revisar o cap1

**Comment by cassiobotaro** [comment]
iniciei o capítulo 2

**Comment by drgarcia1986** [comment]
vou fazer o cap3

**Comment by cassiobotaro** [comment]
Amanhã finalizo o capítulo 2 e irei fazer o 4

**Comment by cassiobotaro** [comment]
Iniciando capítulo 5

**Comment by cassiobotaro** [comment]
capítulo 5 e 6 done!
